modLoader="javafml"
loaderVersion="[4,)"
license="GNU General Public License version 3 (GPLv3)"

[[mods]]
modId="enderworld"
version="26.3.7"
displayName="EnderWorld"
displayURL="https://modrinth.com/mod/crazenmcsenderworld"
logoFile="logo.png"
credits="Thanks to Adobus & Argentum541 for help"
authors="CrazenMC"
description="Mod makes The End much better"

# Start of user code block mod configuration
# End of user code block mod configuration

[[mixins]]
    config = "enderworld.mixins.json"

# Start of user code block custom mixins
# End of user code block custom mixins

[[dependencies.enderworld]]
    modId="neoforge"
    type="required"
    versionRange="[21.8.31,)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.enderworld]]
    modId="minecraft"
    type="required"
    versionRange="[1.21.8]"
    ordering="AFTER"
    side="BOTH"




# Start of user code block dependencies configuration
# End of user code block dependencies configuration